language: node_js
node_js:
- '4.0'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_dd2e0efd98dd_key -iv $encrypted_dd2e0efd98dd_iv -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_travis
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'kazaff'
- git config --global user.email 'kazaff@gmail.com'
- git clone git@github.com:kazaff/travis-hexo.git .deploy
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo d
