language: node_js
node_js:
- '4.0'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_dd2e0efd98dd_key -iv $encrypted_dd2e0efd98dd_iv
  -in id_rsa_travis.enc -out ~\/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo
before_script:
- git config --global user.name 'kazaff'
- git config --global user.email 'kazaff@gmail.com'
- git clone git@github.com:kazaff/travis-hexo.git -b gh-pages --single-branch .deploy_git
script:
- hexo generate
after_success:
- hexo d
