# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/kazaff
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive
- recent_posts
- links

# Links
links:
  神秘的程序员们: http://blog.xiqiao.info/category/programmers
  主题作者: http://themes.xiguabaobao.com

# Miscellaneous
google_analytics: UA-35141228-2
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# disqus
disqus_shortname: http-blog-kazaff-me

# Baidu share
baidushare: true
